const START_GET_PRODUCTS = "START_GET_PRODUCTS";
const GET_PRODUCTS = "GET_PRODUCTS";
const Error = "Error";
const SHOW_SIDEBAR = "SHOW_SIDEBAR";
const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
const LOAD_PRODUCT ="LOAD_PRODUCT";

export { START_GET_PRODUCTS, GET_PRODUCTS, SHOW_SIDEBAR, CLOSE_SIDEBAR ,Error,LOAD_PRODUCT};
